version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: shortener_db
    restart: always
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: ilyada
      POSTGRES_PASSWORD: 123123
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
